In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'i will get a job this first quarter']

In [11]:
## Define the vocabulary size
voc_size=10000

In [12]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'i will get a job this first quarter']

In [13]:
## one hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8659, 1257, 845, 7854],
 [8659, 1257, 845, 1208],
 [8659, 4901, 845, 7558],
 [3117, 6406, 2337, 3555, 5114],
 [3117, 6406, 2337, 3555, 7376],
 [7707, 8659, 3542, 845, 5224],
 [3117, 1379, 7249, 2337, 8578, 6793, 6566, 9331]]

In [15]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [19]:
## the pad_sequences and padding helps in representing a zero as a balance to the number of words
sent_length=8
embdedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embdedded_docs)

[[   0    0    0    0 8659 1257  845 7854]
 [   0    0    0    0 8659 1257  845 1208]
 [   0    0    0    0 8659 4901  845 7558]
 [   0    0    0 3117 6406 2337 3555 5114]
 [   0    0    0 3117 6406 2337 3555 7376]
 [   0    0    0 7707 8659 3542  845 5224]
 [3117 1379 7249 2337 8578 6793 6566 9331]]


In [20]:
## feature representation
dim=10

In [23]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')
model.summary()

/opt/anaconda3/envs/genai_venv/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.predict(embdedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step


array([[[-0.04646562,  0.04103914,  0.01666819, -0.00317271,
          0.01656598, -0.00322397, -0.01984212,  0.02737712,
         -0.01296431,  0.02065636],
        [-0.04646562,  0.04103914,  0.01666819, -0.00317271,
          0.01656598, -0.00322397, -0.01984212,  0.02737712,
         -0.01296431,  0.02065636],
        [-0.04646562,  0.04103914,  0.01666819, -0.00317271,
          0.01656598, -0.00322397, -0.01984212,  0.02737712,
         -0.01296431,  0.02065636],
        [-0.04646562,  0.04103914,  0.01666819, -0.00317271,
          0.01656598, -0.00322397, -0.01984212,  0.02737712,
         -0.01296431,  0.02065636],
        [ 0.04125849, -0.00634895,  0.02747871,  0.02931261,
         -0.02505407,  0.04409413, -0.02404418,  0.02676816,
          0.04673326,  0.04580576],
        [-0.00895362,  0.00444736, -0.04110302, -0.04030706,
         -0.00698481, -0.02382596, -0.03231211,  0.00653443,
          0.04619816, -0.03312756],
        [ 0.03065987,  0.04905948,  0.00093514, -0.0